# Generated by Django 5.2.17 on 2026-09-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mufaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Műfaj',
                'verbose_name_plural': 'MŰfajOk',
            },
        ),
        migrations.CreateModel(
            name='Darab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=100)),
                ('bemutato', models.DateField()),
                ('utolso', models.DateField()),
                ('hanyszor', models.IntegerField()),
                ('nezoszam', models.IntegerField()),
                ('mufaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hetedik.mufaj')),
            ],
            options={
                'verbose_name': 'Darab',
                'verbose_name_plural': 'DarabOK',
            },
        ),
    ]
