# Generated by Django 5.2.17 on 2026-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hetedik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mufaj',
            name='ajdi',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
