# Generated by Django 5.2.17 on 2026-09-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hetedik', '0002_mufaj_ajdi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mufaj',
            new_name='Mufajka',
        ),
    ]
