# Generated by Django 5.2.17 on 2026-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hetedik', '0003_rename_mufaj_mufajka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darab',
            name='bemutato',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='darab',
            name='hanyszor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='darab',
            name='nezoszam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darab',
            name='utolso',
            field=models.DateField(auto_now=True),
        ),
    ]
