# Generated by Django 5.2.17 on 2026-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hetedik', '0004_alter_darab_bemutato_alter_darab_hanyszor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darab',
            name='bemutato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='darab',
            name='utolso',
            field=models.DateField(),
        ),
    ]
